# Generated by Django 4.2.4 on 2026-06-27 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_location', models.CharField(max_length=200, verbose_name='Searched Location')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Temperature (°C)')),
                ('humidity', models.IntegerField(verbose_name='Humidity (%)')),
                ('rainfall', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Rainfall (mm)')),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Wind Speed (km/h)')),
                ('condition', models.CharField(max_length=100, verbose_name='Condition')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Searched Date/Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
