# Generated by Django 4.2.4 on 2026-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weatherhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('Cotton', 'Cotton (કપાસ)'), ('Groundnut', 'Groundnut (મગફળી)'), ('Maize', 'Maize (મકાઈ)'), ('Bajra', 'Bajra (બાજરી)'), ('Wheat', 'Wheat (ઘઉં)'), ('Castor', 'Castor (દિવેલા)'), ('Cumin', 'Cumin (જીરું)'), ('Mustard', 'Mustard (રાઈ)')], max_length=50, verbose_name='Crop Name')),
                ('mandi_name', models.CharField(max_length=100, verbose_name='Mandi Name (APMC)')),
                ('today_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Today Price (₹/Quintal)')),
                ('yesterday_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yesterday Price (₹/Quintal)')),
                ('price_date', models.DateField(verbose_name='Price Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'ordering': ['-price_date', 'crop_name'],
            },
        ),
    ]
