# Generated by Django 4.2.4 on 2026-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mandiprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandiprice',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Price (₹/Quintal)'),
        ),
        migrations.AddField(
            model_name='mandiprice',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Price (₹/Quintal)'),
        ),
    ]
