# Generated by Django 4.2.4 on 2026-06-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cotton', 'Cotton (કપાસ)'), ('Groundnut', 'Groundnut (મગફળી)'), ('Maize', 'Maize (મકાઈ)'), ('Bajra', 'Bajra (બાજરી)'), ('Wheat', 'Wheat (ઘઉં)'), ('Castor', 'Castor (દિવેલા)'), ('Cumin', 'Cumin (જીરું)'), ('Mustard', 'Mustard (રાઈ)')], max_length=50, verbose_name='Crop Name')),
                ('variety', models.CharField(max_length=100, verbose_name='Crop Variety')),
                ('sowing_date', models.DateField(verbose_name='Sowing Date')),
                ('expected_harvest_date', models.DateField(verbose_name='Expected Harvest Date')),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Land Size (Acres)')),
                ('investment_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Investment Cost (₹)')),
                ('expected_yield', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Expected Yield (Quintals)')),
                ('estimated_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Estimated Revenue (₹)')),
                ('status', models.CharField(choices=[('Growing', 'Growing (વિકસી રહ્યું છે)'), ('Ready to Harvest', 'Ready to Harvest (લણણી માટે તૈયાર)'), ('Harvested', 'Harvested (લણણી પૂર્ણ)')], default='Growing', max_length=20, verbose_name='Crop Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crop_images/', verbose_name='Crop Image')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sowing_date'],
            },
        ),
    ]
