# Generated by Django 4.2.4 on 2026-06-27 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50, verbose_name='Crop Name')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature (°C)')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidity (%)')),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rainfall (mm)')),
                ('soil_type', models.CharField(max_length=50, verbose_name='Soil Type')),
                ('ml_model', models.CharField(max_length=50, verbose_name='ML Model')),
                ('disease', models.CharField(max_length=100, verbose_name='Predicted Disease')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Confidence Score (%)')),
                ('treatment', models.TextField(verbose_name='Treatment Recommended')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Prediction Date')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
