# Generated by Django 4.2.4 on 2026-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_diseaseprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseprediction',
            name='crop_name',
            field=models.CharField(choices=[('Cotton', 'Cotton (કપાસ)'), ('Groundnut', 'Groundnut (મગફળી)'), ('Maize', 'Maize (મકાઈ)'), ('Bajra', 'Bajra (બાજરી)'), ('Wheat', 'Wheat (ઘઉં)'), ('Castor', 'Castor (દિવેલા)'), ('Cumin', 'Cumin (જીરું)'), ('Mustard', 'Mustard (રાઈ)')], max_length=50, verbose_name='Crop Name'),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='soil_type',
            field=models.CharField(choices=[('Black', 'Black Soil (કાળી જમીન)'), ('Sandy', 'Sandy Soil (રેતાળ જમીન)'), ('Alluvial', 'Alluvial Soil (કાંપવાળી જમીન)'), ('Clayey', 'Clayey Soil (ચીકણી જમીન)'), ('Loamy', 'Loamy Soil (ગોરાડુ જમીન)')], max_length=50, verbose_name='Soil Type'),
        ),
    ]
