# Generated by Django 4.2.4 on 2026-06-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_alter_diseaseprediction_crop_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Crop Name')),
                ('gujarati_name', models.CharField(max_length=100, verbose_name='Gujarati Name')),
                ('season', models.CharField(choices=[('Kharif', 'Kharif (ખરીફ)'), ('Rabi', 'Rabi (રવિ)'), ('Zaid', 'Zaid (જાયદ)')], max_length=10, verbose_name='Season')),
                ('soil_type', models.CharField(max_length=150, verbose_name='Soil Type')),
                ('temperature_range', models.CharField(max_length=100, verbose_name='Temperature Range')),
                ('rainfall_requirement', models.CharField(max_length=100, verbose_name='Rainfall Requirement')),
                ('sowing_time', models.CharField(max_length=100, verbose_name='Sowing Time')),
                ('harvest_time', models.CharField(max_length=100, verbose_name='Harvest Time')),
                ('expected_yield', models.CharField(max_length=150, verbose_name='Expected Yield')),
                ('common_diseases', models.TextField(verbose_name='Common Diseases')),
                ('suitable_fertilizers', models.TextField(verbose_name='Suitable Fertilizers')),
                ('image_path', models.CharField(blank=True, max_length=255, verbose_name='Static Image Path')),
            ],
        ),
    ]
