# Generated by Django 4.2.4 on 2026-06-30 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0004_croplibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('Cotton', 'Cotton (કપાસ)'), ('Wheat', 'Wheat (ઘઉં)'), ('Groundnut', 'Groundnut (મગફળી)'), ('Maize', 'Maize (મકાઈ)'), ('Bajra', 'Bajra (બાજરી)'), ('Castor', 'Castor (દિવેલા)'), ('Cumin', 'Cumin (જીરું)'), ('Mustard', 'Mustard (રાઈ)')], max_length=50, verbose_name='Crop Name')),
                ('soil_type', models.CharField(choices=[('Black Soil', 'Black Soil (કાળી જમીન)'), ('Sandy Soil', 'Sandy Soil (રેતાળ જમીન)'), ('Alluvial Soil', 'Alluvial Soil (કાંપવાળી જમીન)'), ('Red Soil', 'Red Soil (લાલ જમીન)')], max_length=50, verbose_name='Soil Type')),
                ('crop_stage', models.CharField(choices=[('Sowing/Basal', 'Sowing / Basal Stage (વાવણી / પાયાનો તબક્કો)'), ('Vegetative', 'Vegetative Growth (વાનસ્પતિક વૃદ્ધિ)'), ('Flowering/Fruiting', 'Flowering / Fruiting (ફૂલ / ફળ બેસવાનો તબક્કો)')], max_length=50, verbose_name='Crop Stage')),
                ('fertilizer_name', models.CharField(max_length=150, verbose_name='Recommended Fertilizer')),
                ('npk_ratio', models.CharField(max_length=50, verbose_name='NPK Ratio')),
                ('quantity_per_acre', models.CharField(max_length=100, verbose_name='Quantity per Acre')),
                ('application_method', models.CharField(max_length=100, verbose_name='Application Method')),
                ('best_time', models.CharField(max_length=150, verbose_name='Best Application Time')),
                ('safety_precautions', models.TextField(verbose_name='Safety Precautions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recommendation Date')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
