# Generated by Django 4.2.4 on 2026-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_fertilizerrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='News Title')),
                ('link', models.CharField(max_length=255, unique=True, verbose_name='Source URL')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='News Image URL')),
                ('summary', models.TextField(verbose_name='Short Summary')),
                ('pub_date', models.CharField(max_length=100, verbose_name='Published Date')),
                ('source_name', models.CharField(max_length=100, verbose_name='Source Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fetched Date')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
